export const defaultContent = {
  seoTitle: 'Florent Moulin | Solopreneur assisté par IA',
  metaDescription: 'Je conçois et lance des sites web, SaaS, automatisations IA et outils métiers pour entrepreneurs, startups et entreprises.',
  ogTitle: 'Florent Moulin | Solopreneur assisté par IA',
  ogDescription: 'Je conçois et lance des sites web, SaaS, automatisations IA et outils métiers pour entrepreneurs, startups et entreprises.',
  heroTitle: 'Je construis des projets digitaux avec la puissance de l’IA.',
  heroSubtitle: 'Solopreneur assisté par IA, j’aide les entrepreneurs et entreprises à transformer rapidement leurs idées en sites, SaaS, automatisations et plateformes concrètes.',
  primaryCta: 'Discuter de mon projet',
  secondaryCta: 'Voir le portfolio',
  presentationTitle: 'Un studio digital solopreneur assisté par IA.',
  presentationText: 'Mills Rocket n’est pas une grosse agence. C’est un studio porté par une seule vision, avec moins d’intermédiaires et plus d’efficacité.\n\nLe client travaille avec une personne qui comprend le business, conçoit le produit et pilote l’exécution, pas avec une chaîne d’intervenants déconnectés. L’objectif n’est pas de vendre du temps, mais de livrer un projet utile, concret et exploitable.',
  aiPositioningTitle: 'Un solopreneur assisté par IA',
  aiPositioningText: 'Mills Rocket repose sur une conviction simple : aujourd’hui, une personne bien organisée, bien équipée et assistée par l’IA peut créer plus vite, tester plus vite et lancer plus vite. J’utilise l’IA pour accélérer l’analyse, le développement, le contenu, le SEO, l’automatisation et l’optimisation des projets.',
  aiCards: [
    { title: 'Vision business', text: 'Une seule personne garde le contexte, comprend l’objectif et relie les choix techniques aux enjeux business.' },
    { title: 'Développement rapide', text: 'L’IA accélère la conception, le code, les itérations et la production des premières versions exploitables.' },
    { title: 'Automatisation IA', text: 'Les workflows IA servent à automatiser les tâches répétitives, structurer les données et gagner en efficacité.' },
    { title: 'Lancement concret', text: 'Le focus reste la mise en ligne, le SEO, les contenus, les tests et l’amélioration après livraison.' },
  ],
  founderTitle: 'Qui est derrière Mills Rocket ?',
  founderText: 'Je m’appelle Florent Moulin.\n\nDepuis plus de 10 ans, je crée des sites web, développe des outils digitaux et accompagne des entreprises dans leurs projets numériques.\n\nJ’ai travaillé dans le développement web, le recrutement, le business development, l’immobilier, le marketing digital et la création d’entreprises.\n\nAujourd’hui, j’ai choisi un modèle différent : celui du solopreneur assisté par l’IA.\n\nGrâce aux outils d’intelligence artificielle, je peux concevoir, développer et lancer des projets beaucoup plus rapidement qu’une structure traditionnelle.\n\nMon objectif n’est pas de vendre du temps mais de créer des solutions concrètes qui répondent à un besoin réel.\n\nJe développe également mes propres projets afin de tester en permanence de nouvelles idées, technologies et stratégies de lancement.',
  founderImage: '/florent-moulin-founder.jpg',
  founderName: 'Florent Moulin',
  founderRole: 'Fondateur de Mills Rocket',
  founderProjects: ['Spotykite', 'Signal Immo', 'MillsBank', 'Mills Rocket Lab'],
  expertiseTitle: 'Mes domaines d’expertise',
  expertiseItems: ['Développement web', 'Plateformes SaaS', 'Intelligence artificielle', 'Automatisation', 'SEO', 'E-commerce', 'Acquisition digitale', 'Analyse et optimisation de processus'],
  whySolopreneurTitle: 'Pourquoi travailler avec un solopreneur ?',
  whySolopreneurCards: [
    { title: 'Vision unique', text: 'Un seul interlocuteur du début à la fin.' },
    { title: 'Exécution rapide', text: 'Moins de réunions, plus d’action.' },
    { title: 'Assisté par l’IA', text: 'Utilisation quotidienne des meilleurs outils IA pour accélérer le développement.' },
    { title: 'Culture entrepreneuriale', text: 'Je développe également mes propres startups et connais les réalités du terrain.' },
  ],
  founderQuote: 'Je ne vends pas des heures de développement. Je construis des projets capables de créer de la valeur.',
  founderQuoteAuthor: '— Florent Moulin\nFondateur de Mills Rocket',
  homeServicesTitle: 'Des briques concrètes pour construire, lancer et améliorer.',
  homeServicesText: 'Chaque projet peut être traité comme une mission client, un MVP ou une expérimentation rapide selon votre niveau de maturité.',
  methodTitle: 'Un processus court, lisible et orienté livraison.',
  methodSteps: ['Analyse du besoin', 'Proposition claire', 'Développement rapide', 'Mise en ligne', 'Optimisation'],
  portfolioTitle: 'Des projets variés, du produit au business.',
  portfolioText: 'Ces références illustrent la polyvalence recherchée: produit, développement, automatisation, acquisition, e-commerce et image de marque.',
  solutionsTitle: 'Des solutions pensées pour les entrepreneurs qui veulent avancer.',
  solutionsText: 'Pas de tunnel inutile. On part du besoin business, puis on construit la version la plus utile pour tester, vendre ou automatiser.',
  labTitle: 'Un espace pour tester, construire et lancer régulièrement.',
  labText: 'Le Lab Mills Rocket rassemble les projets internes, expérimentations IA, prototypes SaaS, explorations crypto, automatisations et pistes e-commerce. C’est une manière de rester au contact du terrain: tester des idées, apprendre vite, garder ce qui fonctionne.',
  labItems: [
    'Expérimentations IA appliquées aux tâches business',
    'Prototypes SaaS testés sur des cas concrets',
    'Automatisations de prospection, contenu et reporting',
    'Pistes e-commerce, SEO programmatique et outils internes',
    'Explorations crypto, finance décentralisée et nouveaux modèles produit',
  ],
  contactTitle: 'Vous avez une idée ? On peut la transformer en produit lancé.',
  contactText: 'Décrivez votre projet, votre contexte et ce que vous voulez obtenir. Je reviens vers vous avec une lecture claire du besoin et une première direction concrète.',
};

export const defaultSolutions = [
  ['Sites vitrines premium', 'Des sites premium, rapides et orientés conversion pour rendre une activité claire, crédible et visible.', 'Identité, structure, contenus, design responsive et optimisation SEO pour présenter une offre avec précision et générer des demandes qualifiées.', 'Globe2', 1],
  ['Plateformes web', 'Des interfaces métier, espaces clients, dashboards et parcours web adaptés à vos opérations.', 'Portails, marketplaces, espaces membres, outils de réservation ou interfaces complexes conçus autour de vos vrais usages.', 'Layers3', 2],
  ['SaaS métiers', 'De l’idée au MVP exploitable, avec une logique produit, des itérations courtes et une mise en ligne rapide.', 'MVP, back-office, tableaux de bord, gestion d’abonnements et fonctionnalités clés pour tester vite un modèle produit.', 'Code2', 3],
  ['Automatisation IA', 'Des workflows IA pour réduire les tâches manuelles, qualifier, générer, analyser ou synchroniser vos données.', 'Agents, assistants, enrichissement de données, génération de contenu, scoring, notifications et synchronisations entre outils.', 'Bot', 4],
  ['Outils internes', 'Des outils simples pour remplacer les fichiers dispersés, automatiser les routines et donner une vision claire aux équipes.', 'Des outils simples pour remplacer les fichiers dispersés, automatiser les routines et donner une vision claire aux équipes.', 'Workflow', 5],
  ['E-commerce', 'Boutiques, tunnels, paiements, contenus et automatisations pour vendre plus simplement.', 'WooCommerce, parcours d’achat, pages produits, emails, analytics et automatisations pour vendre sans usine à gaz.', 'ShoppingCart', 6],
  ['SEO / acquisition', 'Une base technique propre, des contenus utiles et des actions concrètes pour gagner en visibilité.', 'Architecture, mots-clés, pages de conversion, tracking et boucles d’amélioration pour attirer le bon trafic.', 'Target', 7],
];

export const defaultReferences = [
  ['Spotykite', 'Plateforme de réservation', 'Plateforme de réservation de stages de kitesurf pensée pour connecter pratiquants, écoles et disponibilités.', 'Plateforme de réservation de stages de kitesurf avec approche produit, parcours utilisateur et logique d’acquisition.', 'Produit, Plateforme web, Réservation, SEO', 'en développement', '/millsrocket-og.png', '', 1],
  ['Signal Immo', 'Outil de prospection terrain', 'Outil de prospection immobilière terrain pour repérer, structurer et prioriser des opportunités locales.', 'Outil métier pour organiser la prospection terrain, suivre les opportunités et transformer les signaux locaux en actions concrètes.', 'SaaS métier, Cartographie, Workflow, Data', 'lancé', '/millsrocket-og.png', '', 2],
  ['Millscoin / MillsBank', 'Crypto / finance décentralisée', 'Expérimentation autour de la finance décentralisée, des mécanismes crypto et des interfaces produit associées.', 'Projet interne autour des mécaniques crypto, de la finance décentralisée et de la construction de produits financiers digitaux.', 'Web3, Produit, Finance, Prototype', 'en développement', '/millsrocket-og.png', '', 3],
  ['4000m', 'Optimisation commerciale', 'Travail sur l’optimisation commerciale, la structuration de partenaires et les leviers de croissance.', 'Accompagnement orienté business pour clarifier les leviers commerciaux, structurer les partenaires et prioriser les actions utiles.', 'Business, Acquisition, Partenariats, Stratégie', 'référence client', '/millsrocket-og.png', '', 4],
  ['Christine Nicolas', 'WordPress / WooCommerce', 'Site WordPress avec WooCommerce pour valoriser une offre, vendre des audios et gérer une présence digitale claire.', 'Création et optimisation d’un site WordPress / WooCommerce pour vendre des contenus audio et clarifier l’offre.', 'WordPress, WooCommerce, Contenu, Conversion', 'référence client', '/millsrocket-og.png', '', 5],
  ['Maison Kabia', 'Site vitrine / image de marque', 'Site vitrine et positionnement digital pour porter une image de marque élégante, claire et mémorable.', 'Site vitrine et image digitale pour donner une présence claire, premium et cohérente à la marque.', 'Branding, Site vitrine, UX, SEO', 'référence client', '/millsrocket-og.png', '', 6],
];
